abbr fishconf "v ~/.config/fish/config.fish"
abbr fishabbr "v ~/.config/fish/shortcuts.fish"
abbr bashrc "v ~/.bashrc"
abbr i3conf "v ~/.config/i3/config"
abbr polyconf "v ~/.config/polybar/config"
abbr vimconf "v ~/.vimrc"
abbr mkdir 'mkdir -p'
abbr sshconf 'v ~/.ssh/config'
abbr dots 'cd ~/.repos/dotfiles'
