#! /bin/sh

bspc monitor LVDS-1 -d 1 2 3 4 5 
bspc monitor VGA-1 -d 6 7 8 9 10

bspc config border_width         2
bspc config window_gap          12
bspc config top_padding 0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc pointer -g focus

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a celluloid state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

#### BSPWM coloring ####
bspc config normal_border_color		      "#4c566a"
bspc config active_border_color	          "#1e1e1e"
bspc config focused_border_color	      "#5e81ac"
bspc config presel_feedback_color	      "#5e81ac"
bspc config urgent_border_color 	      "#dd2727"


# autostart
# --------------------

xsetroot -cursor_name left_ptr
pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x picom > /dev/null || picom --config $HOME/.config/compton.conf -b
pgrep -x polkit-mate-authentication-agent-1 > /dev/null || /usr/libexec/polkit-mate-authentication-agent-1 &
feh --bg-fill $HOME/.wal.png
pgrep -x syncthing > /dev/null || syncthing -no-browser &
pgrep -x dunst > /dev/null || dunst &
xrdb -merge $HOME/.Xresources

# run the xrandr command if an external monitor is connected to the
# laptop.  This must be executed before the polybar command, so that
# polybar can set the two separate bars properly.
if [ -x $HOME/.config/bspwm/monitors.sh ]; then
    $HOME/.config/bspwm/monitors.sh
fi

# NOTE the path to the polybar executable.  This is the default location
# when compiling from source.
if [ -x /usr/bin/polybar ]; then
	bash $HOME/.config/polybar/launch.sh
fi
