#! /bin/sh

bspc monitor LVDS-1 -d 1 2 3 4 5 6 7 8 9 

bspc config border_width         4
bspc config window_gap          12
bspc config top_padding 0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc pointer -g focus

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a mpv state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

#### BSPWM coloring ####
bspc config normal_border_color "#44475a"
bspc config active_border_color "#bd93f9"
bspc config focused_border_color "#ff79c6"
bspc config presel_feedback_color "#6272a4"
bspc config urgent_border_color "#dd2727"


# autostart
# --------------------

xsetroot -cursor_name left_ptr
pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x picom > /dev/null || picom --config $HOME/.config/picom/picom.conf -b
nitrogen --restore
pgrep -x dunst > /dev/null || dunst &
xrdb -merge $HOME/.Xresources
pgrep -x flameshot > /dev/null || flameshot &
pgrep -x xautolock > /dev/null || xautolock -time 10 -locker 'betterlockscreen -l' &

# NOTE the path to the polybar executable.  This is the default location
# when compiling from source.
if [ -x /usr/bin/polybar ]; then
	bash $HOME/.config/polybar/launch.sh
fi
